# Generated by Django 4.0.5 on 2022-07-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('kmreC', models.IntegerField(verbose_name='Km recorridos')),
                ('timeStimed', models.CharField(max_length=100, verbose_name='Tiempo estimado')),
                ('puntoIni', models.CharField(max_length=200, verbose_name='Punto de inicio')),
                ('costo', models.IntegerField(verbose_name='Costo')),
                ('foto', models.ImageField(null=True, upload_to='fotos', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
