# Generated by Django 4.0.5 on 2022-07-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['-created'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AddField(
            model_name='tours',
            name='fechaIni',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
