# Generated by Django 4.0.5 on 2022-07-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_tours_options_tours_fechaini'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(max_length=100, verbose_name='Correo')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('imagen', models.ImageField(null=True, upload_to='fotosUser', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Contacto',
                'verbose_name_plural': 'Comentarios Contactos',
                'ordering': ['-created'],
            },
        ),
    ]
