# Generated by Django 4.0.5 on 2022-07-23 20:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_comentariousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
