# Generated by Django 4.0.5 on 2022-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_tours_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.TextField(verbose_name='Descripcion')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='comentariousuario',
            name='imagen',
        ),
    ]
