# Generated by Django 4.0.5 on 2022-07-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_archivos_remove_comentariousuario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivos',
            old_name='email',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='archivos',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
