# Generated by Django 4.0.5 on 2022-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_rename_email_archivos_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivos',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='archivos',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='mensaje',
            field=models.TextField(null=True, verbose_name='Mensaje'),
        ),
    ]
