# Generated by Django 4.0.5 on 2022-08-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_rename_update_archivos_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Realizado'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre_c', models.TextField(verbose_name='Nombre')),
                ('apellido_p', models.TextField(verbose_name='Apellido paterno')),
                ('apellido_m', models.TextField(verbose_name='Apellido materno')),
                ('correo_c', models.CharField(max_length=70, verbose_name='Correo')),
                ('celular', models.IntegerField(max_length=10, verbose_name='Celular')),
                ('mensaje_c', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('tour_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.tours', verbose_name='Tours')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created'],
            },
        ),
    ]
