# Generated by Django 4.0.5 on 2022-08-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_tours_status_alter_tours_id_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='celular',
        ),
    ]
