# Generated by Django 4.0.5 on 2022-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_remove_clientes_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono_c',
            field=models.CharField(default='123', max_length=10, verbose_name='Telefono'),
        ),
    ]
