# Generated by Django 4.0.5 on 2022-08-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_clientes_telefono_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='STATUS (al desmarcar desaparecerá de "Tours")'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='status',
            field=models.BooleanField(default=True, verbose_name='PROXIMOS (al desmarcar se mostrara como un recorrido "Realizado")'),
        ),
    ]
